<?php
namespace app\index\model;
use think\Model;
class IndexModel extends Model{
    protected $table='tw_order';
    protected $field='order_num,pro_num,name,color,price,order_time,status,track_num';
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}